In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = 5

In [5]:
c = a ^ b
c

array([ 4,  7,  6,  1,  0,  3,  2, 13, 12])

In [7]:
c ^ b # = a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
c ^ a # = b

array([5, 5, 5, 5, 5, 5, 5, 5, 5])

In [9]:
d = np.array([5, 5, 5, 5, 5, 5, 5, 5, 5])
a ^ d

array([ 4,  7,  6,  1,  0,  3,  2, 13, 12])

In [10]:
a[4] ^ b

0